// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ArchEngBot",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "ArchEngBot",
            targets: ["AppModule"],
            bundleIdentifier: "com.archengbot.app",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .microphone(purposeString: "App cần truy cập micro để ghi âm giọng đọc của bạn và chấm điểm phát âm bằng AI.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Resources/Config.json.example"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
